- name: 'install latest qemu-guest-agent'
  hosts: '*'
  tasks:
    - name: 'Install qemu-guest-agent'
      apt:
        name: 'Install qemu-guest-agent'
        state: present
        update_cache: true
      become: 'yes'